# --- SECCIÓN OBLIGATORIA DE EVENTOS ---
events {
    worker_connections 1024; # Número máximo de conexiones simultáneas
}

# Configuración del módulo RTMP
rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application live {
            live on;
            record off;

            # --- CONFIGURACIÓN PARA M3U8 (HLS) ---
            hls on;
            hls_path "/home/ns/nsp/rtmp-server/hls"; 
            
            hls_fragment 2s;          
            hls_playlist_length 10s;  
            hls_type live;            

            allow publish all;
            allow play all;
        }
    }
}

# Configuración del servidor HTTP
http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen       8080;
        server_name  localhost;

        location /hls {
            root "/home/ns/nsp/rtmp-server"; 
            add_header Access-Control-Allow-Origin *;
        }
    }
}
