worker_processes auto;

# 1. BLOQUE OBLIGATORIO: Events
events {
    # Un valor razonable si no tiene requisitos especiales
    worker_connections 1024; 
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            # --- NUEVA CONFIGURACIÓN HLS ---
            hls on;
            hls_path /tmp/hls; # Directorio donde Nginx guardará los segmentos .ts
            hls_fragment 5s;    # Tamaño de cada segmento
            hls_playlist_length 15s; # Longitud total de la lista de reproducción
            # -----------------------------
        }
    }
}

# --- NUEVO BLOQUE HTTP (Servidor web) ---
http {
    server {
        listen 8080; # Puedes elegir cualquier puerto HTTP disponible (ej. 80, 8080)

        location /hls {
            # Ruta de donde leerá Nginx los archivos .ts y .m3u8
            root /tmp; 
            # Esto permitirá el acceso externo. Desactívelo en producción si no es necesario.
            add_header Cache-Control no-cache;
            # Para permitir que cualquier dominio incruste el video
            add_header Access-Control-Allow-Origin *;
        }
    }
}
